llm:
  api_type: "openai"  # or azure / ollama / groq etc.
  base_url: "https://api.openai.com/v1"
  api_key: 
  model: "gpt-4-turbo"  # or gpt-3.5-turbo

models:
 "o1-mini-2024-09-12": # model: "gpt-4-turbo"  # or gpt-3.5-turbo
   api_type: "openai"  # or azure / ollama / groq etc.
   base_url: "https://api.openai.com/v1"
   api_key: 
   temperature: 0
 "DeepSeek-R1":
   api_type: "deepinfra"  # or azure / ollama / groq etc.
   base_url: "https://api.deepinfra.com/v1/openai"
   api_key: 
   temperature: 0
#  "DeepSeek-R1-Distill-Qwen-14B":  
#    api_type: "localapi"  
#    base_url: "http://0.0.0.0:8356/v1"
#    api_key: 
#    temperature: 0
CALC_USAGE: True 